fix euslisp: FTBFS: jpegmemcd.c:29:3: error: implicit declaration of function ‘jpeg_memio_dest’
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1066307

This is most likely caused by a change in dpkg 1.22.6, that enabled
-Werror=implicit-function-declaration. For more information, see
https://wiki.debian.org/qa.debian.org/FTBFS#A2024-03-13_-Werror.3Dimplicit-function-declaration