lisp/c/eusioctl.c: use termios.h instead of termio.h as this is old incldue file
fix for debia:unstable-slim,

(cd c;  gcc -c -Wno-old-style-definition  -fPIC -Dx86_64 -DLinux -D_REENTRANT -DVERSION="9.31" -DLIB6 -falign-functions=8 -g -m64 -DTHREADED -DPTHREAD -DX_V11R6_1 -DGCC -DGCC3 -I/usr/include -I/usr/X11R6/include -I/ws/euslisp/include -o /ws/euslisp/Linux64/obj/eusioctl.o -O2 eusioctl.c)
eusioctl.c:12:10: fatal error: termio.h: No such file or directory
   12 | #include <termio.h>
      |          ^~~~~~~~~~