Revert "eval.c: fix 'eval.c:1317:12: error: too many arguments to function 'ifunc'; expected 0, have 32' for i386"
This reverts commit bddff0fc4da7d8060b0f2ac45b5b02fd4d0ac4dd.